// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed ramix.png
var resourceRamixPngData []byte
var resourceRamixPng = &fyne.StaticResource{
	StaticName:    "ramix.png",
	StaticContent: resourceRamixPngData,
}
